variant: fcos
version: 1.5.0
systemd:
  units:
    - name: copy-kubeconfig.service
      enabled: true
      contents: |-
        [Unit]
        Description=Copy kubeconfig for admin access
        After=network-online.target syslog.target setup-kubeadm.service
        Wants=network-online.target setup-kubeadm.service
        Requires=setup-kubeadm.service

        [Service]
        Type=oneshot
        TimeoutStartSec=2400
        Environment=KUBECONFIG='/etc/kubernetes/admin.conf'

        ExecStart=/bin/sh -c '\
          mkdir -p /root/.kube; \
          cp -f /etc/kubernetes/admin.conf /root/.kube/config; \
          chmod 600 /root/.kube/config;'
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target
